# Generated by Django 4.1.6 on 2023-03-07 07:05

from django.db import migrations
import csv
from advisor.models import Trip
from django.db import transaction

def load_data(apps, schema_editor):
    with open('advisor/resources/database_final.csv', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            with transaction.atomic():
                trip = Trip(country=row[0],
                    city=row[1],
                    category=row[2],
                    place_name=row[3],
                    description=row[4],
                    latitude=row[5],
                    longitude=row[6],)
                trip.save()

class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]